# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_feed_max_num', models.IntegerField(default=2, verbose_name='可寄养最大数量')),
                ('can_pet_touch', models.CharField(choices=[('bed', '床'), ('bedroom', '卧室'), ('safa', '沙发')], default='safa', max_length=64, verbose_name='宠物可接触')),
                ('can_pet_use', models.TextField(default='餐盘', verbose_name='宠物可使用')),
            ],
        ),
        migrations.CreateModel(
            name='BasicLodgeServiceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_dog_price_per_day', models.FloatField(default='40.0', verbose_name='小型犬每日寄养费用')),
                ('mid_dog_price_per_day', models.FloatField(default='80.0', verbose_name='中型犬每日寄养费用')),
                ('big_dog_price_per_day', models.FloatField(default='100.0', verbose_name='大型犬每日寄养费用')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_nick_name', models.CharField(max_length=128, verbose_name='家庭昵称')),
                ('home_of_city', models.CharField(max_length=128, verbose_name='城市')),
                ('home_address_detail', models.CharField(max_length=128, verbose_name='家庭详细地址')),
                ('home_facility', models.CharField(max_length=128, verbose_name='家庭配套设施')),
                ('home_members_num', models.IntegerField(default=1, verbose_name='家庭成员数量')),
                ('is_have_pet_zone', models.BooleanField(default=True, verbose_name='是否有宠物活动区域')),
                ('is_have_old_man', models.BooleanField(default=True, verbose_name='是否有老人')),
                ('is_have_child', models.BooleanField(default=True, verbose_name='是否有儿童')),
            ],
        ),
        migrations.CreateModel(
            name='HomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=512, verbose_name='照片名称')),
                ('url_height', models.PositiveIntegerField(default=75)),
                ('url_width', models.PositiveIntegerField(default=75)),
                ('image', models.ImageField(height_field='url_height', upload_to='images/home/%Y/%m', width_field='url_width')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.HomeBasicInfo', verbose_name='寄养家庭')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_than_7_days', models.CharField(default='8.0', max_length=32, verbose_name='大于30天')),
            ],
        ),
        migrations.CreateModel(
            name='PersionBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persion_name', models.CharField(max_length=128, verbose_name='寄养服务人名称')),
                ('persion_sex', models.CharField(choices=[('M', '男'), ('W', '女')], default='M', max_length=64, verbose_name='性别')),
                ('persion_birthday', models.DateField(verbose_name='出生日期')),
                ('phone_number', models.CharField(max_length=512, verbose_name='电话号码')),
                ('feed_exp_pet_type', models.CharField(blank=True, default='', max_length=512, verbose_name='曾养宠物类型')),
                ('feed_exp_pet_yesrs', models.CharField(blank=True, default='', max_length=128, verbose_name='曾养宠物时间')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='family.HomeBasicInfo', verbose_name='寄养家庭')),
            ],
        ),
        migrations.CreateModel(
            name='PersonIdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=512, verbose_name='照片名称')),
                ('id_card_number', models.CharField(max_length=512, verbose_name='身份证号码')),
                ('id_card_front_url_height', models.PositiveIntegerField(default=225)),
                ('id_card_front_url_width', models.PositiveIntegerField(default=225)),
                ('id_card_back_url_height', models.PositiveIntegerField(default=225)),
                ('id_card_back_url_width', models.PositiveIntegerField(default=225)),
                ('id_card_front', models.ImageField(height_field='id_card_front_url_height', upload_to='images/person/id_card/%Y/%m', width_field='id_card_front_url_width')),
                ('id_card_back', models.ImageField(height_field='id_card_back_url_height', upload_to='images/person/id_card/%Y/%m', width_field='id_card_back_url_width')),
                ('persion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.PersionBasicInfo', verbose_name='寄养服务人')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=512, verbose_name='照片名称')),
                ('url_height', models.PositiveIntegerField(default=75)),
                ('url_width', models.PositiveIntegerField(default=75)),
                ('avar_image', models.ImageField(height_field='url_height', upload_to='images/person/avar/%Y/%m', width_field='url_width')),
                ('persion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.PersionBasicInfo', verbose_name='寄养服务人')),
            ],
        ),
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='宠物名字')),
                ('origin', models.CharField(max_length=512, verbose_name='宠物品种')),
                ('type', models.CharField(choices=[('dog', '狗'), ('cat', '猫')], default='dog', max_length=64, verbose_name='宠物类型')),
                ('sex', models.CharField(choices=[('M', '公'), ('W', '母')], default='M', max_length=64, verbose_name='宠物性别')),
                ('avar_image', models.ImageField(upload_to='images/pet/%Y/%m', verbose_name='宠物头像')),
                ('age', models.IntegerField(verbose_name='宠物年龄')),
                ('weight', models.IntegerField(verbose_name='宠物重量')),
                ('vaccin_info_of_4_time', models.DateTimeField(verbose_name='四联注射日期时间')),
                ('vaccin_info_of_4_image', models.ImageField(upload_to='images/pet/%Y/%m', verbose_name='四联证明图片')),
                ('vaccin_info_of_crazy_time', models.DateTimeField(verbose_name='狂犬疫苗注射日期时间')),
                ('vaccin_info_of_crazy_image', models.ImageField(upload_to='images/pet/%Y/%m', verbose_name='狂犬疫苗证明图片')),
                ('insect_inner_time', models.DateTimeField(verbose_name='体内驱虫时间')),
                ('insect_outter_time', models.DateTimeField(verbose_name='体外驱虫时间')),
                ('is_sterilized', models.BooleanField(default=True, verbose_name='是否绝育')),
                ('is_dog_card', models.BooleanField(default=True, verbose_name='是否有狗证')),
                ('dog_card_image', models.ImageField(upload_to='images/pet/%Y/%m', verbose_name='狗证图片')),
                ('is_control_shit', models.BooleanField(default=True, verbose_name='是否能控制大小便')),
                ('is_timid', models.BooleanField(default=True, verbose_name='是否胆小')),
                ('is_tricky', models.BooleanField(default=True, verbose_name='是否调皮')),
                ('is_attack', models.BooleanField(default=True, verbose_name='是否具有攻击性')),
                ('is_peace_with_other_dog', models.BooleanField(default=True, verbose_name='是否与其他狗和谐相处')),
                ('is_peace_with_other_cat', models.BooleanField(default=True, verbose_name='是否与其他猫和谐相处')),
                ('is_peace_with_other_child', models.BooleanField(default=True, verbose_name='是否与儿童和谐相处')),
                ('home', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='family.HomeBasicInfo', verbose_name='寄养家庭')),
            ],
        ),
        migrations.CreateModel(
            name='VipServiceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathe_small_dog_price_per_day', models.FloatField(default='40.0', verbose_name='小型犬每日寄养费用')),
                ('bathe_mid_dog_price_per_day', models.FloatField(default='80.0', verbose_name='中型犬每日寄养费用')),
                ('bathe_big_dog_price_per_day', models.FloatField(default='100.0', verbose_name='大型犬每日寄养费用')),
                ('shuttle_small_dog_price_per_day', models.FloatField(default='40.0', verbose_name='小型犬每日寄养费用')),
                ('shuttle_mid_dog_price_per_day', models.FloatField(default='80.0', verbose_name='中型犬每日寄养费用')),
                ('shuttle_big_dog_price_per_day', models.FloatField(default='100.0', verbose_name='大型犬每日寄养费用')),
                ('good_look_small_dog_price_per_day', models.FloatField(default='40.0', verbose_name='小型犬每日寄养费用')),
                ('good_lookshuttle_mid_dog_price_per_day', models.FloatField(default='80.0', verbose_name='中型犬每日寄养费用')),
                ('good_lookshuttle_big_dog_price_per_day', models.FloatField(default='100.0', verbose_name='大型犬每日寄养费用')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.HomeBasicInfo', verbose_name='寄养家庭')),
            ],
        ),
        migrations.AddField(
            model_name='basiclodgeservicefee',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.HomeBasicInfo', verbose_name='寄养家庭'),
        ),
    ]
