# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import family.models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'verbose_name': '附加信息', 'verbose_name_plural': '附加信息'},
        ),
        migrations.AlterModelOptions(
            name='basiclodgeservicefee',
            options={'verbose_name': '基础寄养服务', 'verbose_name_plural': '基础寄养服务'},
        ),
        migrations.AlterModelOptions(
            name='homebasicinfo',
            options={'verbose_name': '寄养家庭基本信息', 'verbose_name_plural': '寄养家庭基本信息'},
        ),
        migrations.AlterModelOptions(
            name='homephoto',
            options={'verbose_name': '寄养家庭图片', 'verbose_name_plural': '寄养家庭图片'},
        ),
        migrations.AlterModelOptions(
            name='longtermlive',
            options={'verbose_name': '长住优惠', 'verbose_name_plural': '长住优惠'},
        ),
        migrations.AlterModelOptions(
            name='persionbasicinfo',
            options={'verbose_name': '寄养家庭服务人基本信息', 'verbose_name_plural': '寄养家庭服务人基本信息'},
        ),
        migrations.AlterModelOptions(
            name='personidcard',
            options={'verbose_name': '寄养家庭服务人身份证信息', 'verbose_name_plural': '寄养家庭服务人身份证信息'},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'verbose_name': '寄养家庭服务人头像图片', 'verbose_name_plural': '寄养家庭服务人头像图片'},
        ),
        migrations.AlterModelOptions(
            name='petinfo',
            options={'verbose_name': '宠物信息', 'verbose_name_plural': '宠物信息'},
        ),
        migrations.AlterModelOptions(
            name='vipservicefee',
            options={'verbose_name': '增值寄养服务', 'verbose_name_plural': '增值寄养服务'},
        ),
        migrations.AlterField(
            model_name='homephoto',
            name='image',
            field=models.ImageField(height_field='url_height', upload_to='home/%Y/%m', width_field='url_width'),
        ),
        migrations.AlterField(
            model_name='homephoto',
            name='photo_name',
            field=models.CharField(default=family.models.HomePhoto.default_photo_name, max_length=512, verbose_name='照片名称'),
        ),
    ]
