# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20190304_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personphoto',
            old_name='persion',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='personphoto',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='personphoto',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='avar_image',
            field=models.ImageField(upload_to='images/person/avar/%Y/%m'),
        ),
    ]
