# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20190318_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personidcard',
            name='id_card_back',
            field=models.ImageField(height_field='id_card_back_url_height', upload_to='images/person/id_card/%Y/%m', verbose_name='身份证反面', width_field='id_card_back_url_width'),
        ),
        migrations.AlterField(
            model_name='personidcard',
            name='id_card_front',
            field=models.ImageField(height_field='id_card_front_url_height', upload_to='images/person/id_card/%Y/%m', verbose_name='身份证正面', width_field='id_card_front_url_width'),
        ),
    ]
