# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20190318_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='avar_image',
            field=models.ImageField(upload_to='images/pet/avar_image/%Y/%m', verbose_name='宠物头像'),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='dog_card_image',
            field=models.ImageField(upload_to='images/pet/dog_card_image/%Y/%m', verbose_name='狗证图片'),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='vaccin_info_of_4_image',
            field=models.ImageField(upload_to='images/pet/vaccin_info_of_4_image/%Y/%m', verbose_name='四联证明图片'),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='vaccin_info_of_crazy_image',
            field=models.ImageField(upload_to='images/pet/vaccin_info_of_crazy_image/%Y/%m', verbose_name='狂犬疫苗证明图片'),
        ),
    ]
