# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_auto_20190418_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persionbasicinfo',
            old_name='persion_birthday',
            new_name='person_birthday',
        ),
        migrations.RenameField(
            model_name='persionbasicinfo',
            old_name='persion_name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='persionbasicinfo',
            old_name='persion_sex',
            new_name='person_sex',
        ),
    ]
