# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_auto_20190418_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persionbasicinfo',
            options={'verbose_name': '寄养家庭主人基本信息', 'verbose_name_plural': '寄养家庭主人基本信息'},
        ),
        migrations.AlterModelOptions(
            name='personidcard',
            options={'verbose_name': '寄养家庭主人身份证信息', 'verbose_name_plural': '寄养家庭主人身份证信息'},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'verbose_name': '寄养家庭主人头像图片', 'verbose_name_plural': '寄养家庭主人头像图片'},
        ),
        migrations.AlterField(
            model_name='homephoto',
            name='url_height',
            field=models.PositiveIntegerField(default=75, verbose_name='照片高度'),
        ),
        migrations.AlterField(
            model_name='homephoto',
            name='url_width',
            field=models.PositiveIntegerField(default=75, verbose_name='照片宽度'),
        ),
        migrations.AlterField(
            model_name='persionbasicinfo',
            name='person_name',
            field=models.CharField(max_length=128, verbose_name='寄养家庭主人名称'),
        ),
        migrations.AlterField(
            model_name='personidcard',
            name='id_card_back_url_height',
            field=models.PositiveIntegerField(default=225, verbose_name='身份证反面高度'),
        ),
        migrations.AlterField(
            model_name='personidcard',
            name='id_card_back_url_width',
            field=models.PositiveIntegerField(default=225, verbose_name='身份证反面宽度'),
        ),
        migrations.AlterField(
            model_name='personidcard',
            name='id_card_front_url_height',
            field=models.PositiveIntegerField(default=225, verbose_name='身份证正面高度'),
        ),
        migrations.AlterField(
            model_name='personidcard',
            name='id_card_front_url_width',
            field=models.PositiveIntegerField(default=225, verbose_name='身份证正面宽度'),
        ),
        migrations.AlterField(
            model_name='personidcard',
            name='persion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.PersionBasicInfo', verbose_name='寄养家庭主人'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.PersionBasicInfo', verbose_name='寄养家庭主人'),
        ),
    ]
